### PR TITLE
added memorization of latitude/longitude direction

### PR DESCRIPTION
**Pull request by krawczyk87**
If the library stores geographical coordinate values, it is also good to store their directions. Thanks to this, you can recover complete information about the coordinates:

```
fmt.Printf("Latitude GPS: %s %s\n", nmea.FormatGPS(m.Latitude), m.LatDirection)
fmt.Printf("Latitude DMS: %s %s\n", nmea.FormatDMS(m.Latitude), m.LatDirection)
fmt.Printf("Longitude GPS: %s %s\n", nmea.FormatGPS(m.Longitude), m.LonDirection)
fmt.Printf("Longitude DMS: %s %s\n", nmea.FormatDMS(m.Longitude), m.LonDirection)
```

```
Latitude GPS: 5433.2508 N
Latitude DMS: 54° 33' 15.048000" N
Longitude GPS: 1825.6375 E
Longitude DMS: 18° 25' 38.250000" E
```

### CODE REVIEW

**Comment by icholy** [comment]
Can you explain when this would be useful?

**Comment by krawczyk87** [comment]
Currently, after processing the following frames:
```
$GPRMC,110922.000,A,5433.2508,N,01825.6375,E,0.20,124.79,260919,,,D*6B
$GPRMC,110922.000,A,5433.2508,S,01825.6375,W,0.20,124.79,260919,,,D*64
```
the FormatGPS and FormatDMS functions will return the same value for both frames:
```
Raw sentence: $GPRMC,110922.000,A,5433.2508,N,01825.6375,E,0.20,124.79,260919,,,D*6B
Latitude GPS: 5433.2508
Latitude DMS: 54° 33' 15.048000"
Longitude GPS: 1825.6375
Longitude DMS: 18° 25' 38.250000"
Raw sentence: $GPRMC,110922.000,A,5433.2508,S,01825.6375,W,0.20,124.79,260919,,,D*64
Latitude GPS: 5433.2508
Latitude DMS: 54° 33' 15.048000"
Longitude GPS: 1825.6375
Longitude DMS: 18° 25' 38.250000"
```
To find out what direction it is, you need to add a piece of code outside the library. For example, in one of my current projects, in which I plan to use this library, I receive GPS frames on the serial port and I need to stuff another service with coordinates in DMS format, but I also need to include the direction sign. Currently, I would have to add the logic of adding a direction symbol outside the library.

**Comment by icholy** [comment]
This actually won't do what you want because `ParseGPS` flips the sign if the direction is South or West. See https://github.com/adrianmo/go-nmea/blob/4effbc117043858f36774b2848e1fd43f5eda9f1/types.go#L75-L81

So the values you receive will always be North or East regardless of the direction in the original message.

``` go
fmt.Printf("Latitude GPS: %s N\n", nmea.FormatGPS(m.Latitude))
fmt.Printf("Longitude GPS: %s E\n", nmea.FormatGPS(m.Longitude))
```

**Comment by icholy** [comment]
Something like this would probably work:

``` go
func FormatLatGPS(l float64) string {
	dir := North
	if l < 0 {
		dir = South
	}
	return fmt.Sprintf("%f %s", nmea.FormatGPS(l), dir)
}
```

**Comment by krawczyk87** [comment]
Hmm ... nice, less code. I wanted to receive information about the sign itself. So I would like something more like that:

```
func FormatLatSign(l float64) string {
	dir := North
	if l < 0 {
		dir = South
	}
	return dir
}

func FormatLonSign(l float64) string {
	dir := West
	if l < 0 {
		dir = East
	}
	return dir
}
```
Would you add such functions? Or should I present another pull-request with this proposal?

**Comment by icholy** [comment]
TBH I think these functions are so trivial that they're not worth adding.

**Pull request closed without merging**
