### PR TITLE
added latitude range checking

### PR DESCRIPTION
**Pull request by krawczyk87**
third time lucky ;)

### CODE REVIEW

**Comment by icholy** [comment]
@krawczyk87 btw you can put a `[WIP]` prefix on the PR title and squash force-push when you're done. You don't need to keep creating new ones. Just ping me when you think it's ready :)

**Comment by krawczyk87** [comment]
OK thanks. I was just looking for information on how to do this on GitHub.

**Comment by icholy** [comment]
@krawczyk87 just keep pushing to your branch and the PR will automatically update.

**Comment by krawczyk87** [comment]
Yet another suggestion on my part. However, I check the ranges in the LatLong function, which has information about the direction sign (j int). At the same time, I delete the range check in the ParseLatLong function, because this function will lie for longitude anyway. What do you say?

I will improve it to pass coverage / coveralls.

**Comment by icholy** [comment]
I like it

**Comment by krawczyk87** [comment]
Should I add LatLong tests?

**Comment by icholy** [comment]
Yeah, just add some failing tests to `parser_test.go` to get the coverage back up.

**Comment by krawczyk87** [comment]
Okay, I'm ready for judgment :)

**Comment by icholy** [comment]
Looks good, just change the title of the PR ;)

**Comment by krawczyk87** [comment]
Thanks. And thank you for the advices :)

**Comment by icholy** [comment]
Thanks for the contribution!

**Pull request merged**
