### PR TITLE
Remove deprecated messages and tests

### PR DESCRIPTION
**Pull request by icholy**

### CODE REVIEW

**Comment by icholy** [comment]
@adrianmo the problem is the aliases break when using them in type switch.

```
./prog.go:18:2: duplicate case nmea.RMC in type switch
	previous case at ./prog.go:16:2
```
https://play.golang.org/p/BMRDv6n2g2M

``` go
package main

import (
	"fmt"
	"log"

	"github.com/adrianmo/go-nmea"
)

func main() {
	msg, err := nmea.Parse("$GPRMC,220516,A,5133.82,N,00042.24,W,173.8,231.8,130694,004.2,W*70")
	if err != nil {
		log.Fatal(err)
	}
	switch msg.(type) {
	case nmea.GPRMC:
		fmt.Println("GPRMC")
	case nmea.GNRMC:
		fmt.Println("GNRMC")
	}
}
```

**Comment by adrianmo** [comment]
@icholy I don't see why this represents a problem. It's just that you can't use two deprecated prefixes (`GPRMC`, `GNRMC`) that are replaced by the same type (`RMC`). 

My concern is that this is a breaking change that will affect users that haven't updated their prefixes yet. Therefore, I would rather keep the deprecated prefixes until we release a new major version, i.e. v2. 

What do you think?

**Comment by kortschak** [comment]
It's broken already. People that had a switch (e.g. us) had code that that now does not compile since the types were aliased. The change that did the aliasing was a v2 breakage.

**Comment by icholy** [comment]
@adrianmo the problem is that, as @kortschak pointed out, the type aliases broke existing code (type switches). IMO we should merge this and tag a v2.

**Comment by adrianmo** [comment]
Yes, I understand that we already introduced a breaking change when the types were aliased. That was a mistake and it affected **only** to those that were using aliases that were referencing the same type. But if we merge this PR, we will introduce yet another breaking change that will affect anybody that is using **any** of the deprecated aliases, so the impact could be higher. 

The option of merging and releasing a v2 right away doesn't seem right to me. IMO a major version bump should be motivated by a more significant breaking change, not just removing harmless aliases.

I found this interesting text in https://semver.org/:

> **If even the tiniest backwards incompatible changes to the public API require a major version bump, won’t I end up at version 42.0.0 very rapidly?**
> This is a question of responsible development and foresight. Incompatible changes should not be introduced lightly to software that has a lot of dependent code. The cost that must be incurred to upgrade can be significant. Having to bump major versions to release incompatible changes means you’ll think through the impact of your changes, and evaluate the cost/benefit ratio involved.

IMO we could merge it in a v2 branch, that we can maintain in parallel, without making any release, to gain some time and accumulate other breaking changes. 

Any thoughts?

**Comment by icholy** [comment]
@adrianmo separate branch makes sense to me.

**Comment by adrianmo** [comment]
@icholy I've created the `v2.x` branch. Can you please change the base branch in this PR to the new branch? The idea is to merge all breaking changes into that branch and eventually merge it into master and release a v2.0.0.

**Comment by icholy** [comment]
I cherry-picked this into v2.x

**Pull request closed without merging**
