### PR TITLE
DateTime function to convert to time.Time value (close #115)

### LINKED ISSUE #115: Convert nmea.Date and nmea.Time to time.Time
First, thank you for this excellent package. :pray: It's perfectly what I need, and I'm relieved to see it maintained, esp. from developers I recognize!

I'm using it to parse GPS log data from amateur radios.

In particular, I'm finding that it's common to encounter GGA and RMC sentences alternating in a log file. RMC lines have time and date fields; GGA only has time.

I'm wondering if there's a convenient function (or one could be created) that takes both `nmea.Date` and `nmea.Time` and returns a `time.Time`. Once I get my spike code up and running I could contribute this if you think it'd be a good addition.

Edit: Haven't run this yet, but is it just:

```go
time.Date(2000+s.Date.YY, time.Month(s.Date.MM), s.Date.DD,
    s.Time.Hour, s.Time.Minute, s.Time.Second, 0,
    time.UTC)
```

? Or is there more nuance to it?

PS. How do you know the first two digits of the year? I guess by now we can assume the 2000s, but is it possible that any data was collected in the 20th century?

### PR DESCRIPTION
**Pull request by mholt**
This change adds a DateTime function as discussed in #115.

### CODE REVIEW

**Review by icholy — APPROVED** [review]

**Comment by icholy** [comment]
@aldas are you ok with this API?

**Review by aldas — APPROVED** [review]
Only thing here I'm not sure is - should `referenceYear` be first parameter as it is optional and  `d` and `t` are "main" things here but they come after "optional" parameter.

but I trust you more than myself when it comes to creating designing reasonable APIs. 

so LGTM

**Comment by mholt** [comment]
That's a valid point; I guess it's more conventional to have optional arguments last. Refactored and pushed :)

**Review by aldas — DISMISSED** [review]

**Comment by icholy** [comment]
They sorry for the delay, I haven't had access to my computer for the past couple days.

>  should referenceYear be first parameter as it is optional and d and t are "main" things here we are combining but they come after "optional" parameter.

The `referenceYear` parameter isn't optional though, it must be explicitly passed every time. If Go did support optional parameters then putting it last would make sense because you'd be able to omit it at the call site.

``` go
nmea.DateTime(d, t)
```

I put the `referenceYear` first because it's the most significant unit. It's roughly modeled after `time.Date` signature which follows the same left to right pattern.

```go
func Date(year int, month Month, day, hour, min, sec, nsec int, loc *Location) Time
```

I won't die on this hill though. @mholt care to be the tie breaker on this?

**Comment by mholt** [comment]
I guess we technically could do `func DateTime(d Date, t Time, referenceYear ...int) time.Time` to make it optional.

But I think your point about "most significant unit" is a good one, and I like the parity with `time.Date`. Century, year, time. Or put another way: First two year digits, last 2 year digits and rest of date, time.

It's also probably best for this value to be explicitly set. Psychologically speaking, having it be the first argument may be a good way to encourage that.

I just switched it back.

**Comment by mholt** [comment]
Thank you both!!

**Pull request merged**
