### PR TITLE
expose xorChecksum

### PR DESCRIPTION
**Pull request by krasi-georgiev**
expose xorChecksum to be able to use when creating MTK requests.

discussion https://github.com/adrianmo/go-nmea/pull/60#pullrequestreview-271338475

example usage:
https://github.com/arribada/smartLoraTracker/blob/3ae623f282f79d2b2f08045381a9e037d9ff6ab8/tools/gpsLora/gpsLora.go#L57

Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>

### CODE REVIEW

**Comment by icholy** [comment]
If we do expose it, I'd prefer to just call it `Checksum`. `xorChecksum` was a nice name because it let us use `checksum` as a variable in the rest of the code.

**Comment by krasi-georgiev** [comment]
Hm, I think that `XORChecksum` is ok as if there is another Checksum func added in the future it will separate the two.

**Comment by icholy** [comment]
Lol they're not going to add a new checksum to nmea 0183

**Comment by krasi-georgiev** [comment]
I meant a new checksum for any newly added types. It would be preferable to keep the names of the checksum funcs distinct to their actual behavior and not just as generic as `Checksum`

**Comment by icholy** [comment]
XOR is the only checksum used in the standard. If another checksum function was needed for a proprietary message type, that would get a special prefixed name because it's non-standard.

**Comment by krasi-georgiev** [comment]
Ack. Will wait to see  @adrianmo's comments and will refactor.

**Comment by krasi-georgiev** [comment]
Any news on this one?

**Comment by krasi-georgiev** [comment]
ping

**Comment by icholy** [comment]
I'll merge if you rename to `Checksum`.

**Comment by krasi-georgiev** [comment]
done

**Pull request merged**
