### PR TITLE
Added ABM,ACK,ACN,ALC,ALF,ALR,ARC,BBM,HBT,TLB,TTD,VSD sentences

### PR DESCRIPTION
**Pull request by aldas**
* Added ABM,ACK,ACN,ALC,ALF,ALR,ARC,BBM,HBT,TLB,TTD,VSD sentences
* Update CI flow with Go 1.20, action versions, how checkers/linters are installed
* Reorganised README.md Supported sentences table to better visualize which senteces are supporter and which are not, from NMEA/IEC 61162-1 spec

### CODE REVIEW

**Review by icholy — APPROVED** [review]

**Comment by icholy** [comment]
Awesome!

**Comment by icholy** [comment]
@adrianmo you should add @aldas as a contributor.

**Comment by adrianmo** [comment]
That's an awesome contribution @aldas 👏 

As @icholy rightly suggested, I have invited you to join the repo as a collaborator. I hope you'll accept the invitation :)

**Comment by aldas** [comment]
Challenge accepted.

**Pull request merged**
