### PR TITLE
timestamp : Fixed milliseconds timestamp parsing issue.

### PR DESCRIPTION
**Pull request by anekkunt**

### CODE REVIEW

**Comment by icholy** [comment]
@anekkunt can you update the failing test?

**Comment by icholy** [comment]
`Time.String` also needs to change

**Comment by anekkunt** [comment]
>>> Time.String also needs to change 
      No need to change Time.String which is already in a correct format (hh:mm:ss.ss), in this case, milliseconds are represented in seconds i.e 500ms = 0.5 sec

**Comment by icholy** [comment]
``` go
package main

import (
	"fmt"

	"github.com/adrianmo/go-nmea"
)

func main() {
	fmt.Println(nmea.Time{
		Millisecond: 500,
	})
}
```

Outputs: `00:00:00.0500`

**Pull request closed without merging**
