### PR TITLE
add support for PPS, RTK, FRTK fixes in gpgga and gngga

### PR DESCRIPTION
**Pull request by raymandgeoprocessing**
https://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_GGA.html

### CODE REVIEW

**Comment by adrianmo** [comment]
Hi @raymandgeoprocessing, thanks for your contribution. As your changes were breaking the tests, I've taken them and fixed them here: https://github.com/adrianmo/go-nmea/commit/dc2b1ce761f02c6f37b975afc20348b2cc12e8c9

Can you please take my changes and update this PR? I'll merge it once it's done.

Thanks.

**Comment by raymandgeoprocessing** [comment]
> Can you please update this PR with the above changes? I'll merge the PR once it's done.

Not sure how to do that. I've updated the fork.

**Comment by adrianmo** [comment]
@raymandgeoprocessing if it's easier to you, you can open a new PR based on https://github.com/adrianmo/go-nmea/commit/dc2b1ce761f02c6f37b975afc20348b2cc12e8c9, which includes your changes and the necessary fixes to pass the tests.

**Comment by icholy** [comment]
I've opened a new PR with these changes rebased again master. @raymandgeoprocessing  I don't want to take credit, so feel free to copy it if you want.

**Comment by adrianmo** [comment]
I'm closing this PR as @icholy reimplemented this on #16 

@raymandgeoprocessing thanks anyway for the contribution.

**Pull request closed without merging**
